# Generated by Django 4.0.1 on 2022-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
